### ISSUE TITLE
tabline_buffers doesn't work without tabline_tabs

### ISSUE THREAD

**Issue by mystilleef** [kdheepak/tabline.nvim#10]
It's me again. :-D

I don't need `tabline_tabs`. I had it on all this while, solely for testing. After I disabled it, however, `tabline_buffers` only ever shows 1 buffer item.

I think it's best from a usability and design perspective if `tabline_tabs` and `tabline_buffers` behaved as independent `lualine` components. 

Right now, we need to do this for things to work.

```lua
lualine_c = { require'tabline'.tabline_buffers },
lualine_x = { require'tabline'.tabline_tabs },
```

This takes up 2 subsections in `lualine`. 

Ideally, this should work like so.

```lua
lualine_c = { require'tabline'.tabline_buffers, require'tabline'.tabline_tabs },
```

This should also work for users who don't use tabs.

```lua
lualine_c = { require'tabline'.tabline_buffers },
```
In a perfect world, we should be able to stick `tabline_buffers` or `tabline_tabs` anywhere as a `lualine` component and have them behave appropriately, but I understand we don't live in a perfect world. :-) 

I'll settle for option 3 working for now.

**Comment by kdheepak** [comment]
Oof! Thanks for checking my assumptions. It should be fixed now though :)

**Comment by kdheepak** [comment]
> In a perfect world, we should be able to stick tabline_buffers or tabline_tabs anywhere as a lualine component and have them behave appropriately, but I understand we don't live in a perfect world. :-)

I'd like to get to this point.

**Comment by mystilleef** [comment]
WOW! That was fast! I confirm it's fixed. Great job!

This is what my setup looks like, in case you've been wondering why I've been so, ahem, pedantic. :-)

![Screenshot from 2021-08-14 18-45-34](https://user-images.githubusercontent.com/273399/129462039-f1615d95-4cf6-4a87-a7ea-7c1b5d72168f.png)

Thanks for your great work.

**Comment by kdheepak** [comment]
Nice setup, you have a much bigger screen real estate than I do :)

**Comment by kdheepak** [comment]
Maybe it makes sense to show tabs only if there is more than one tab? That way the bufferline can use more space when only one tab is present.

**Comment by mystilleef** [comment]
> Maybe it makes sense to show tabs only if there is more than one tab? That way the bufferline can use more space when only one tab is present.

Great idea. I think most users would appreciate this.

**Comment by kdheepak** [comment]
I fixed a bug in the previous PR and made the tabline show only if the first tab is named or if there more than one tab. There's also a `always_show_tabs` option, if the user wants to always show tabs in the tabline. Thanks for the discussion!

**Comment by kdheepak** [comment]
the buffer and tab components have been merged into shadmansaleh’s fork of lualine: https://github.com/shadmansaleh/lualine.nvim/pull/42

If you aren’t using the buffer binds to tab feature, I’d recommend using the built in components instead.
