### ISSUE TITLE
Closing buffers

### ISSUE THREAD

**Issue by ahmed-rezk-dev** [kdheepak/tabline.nvim#15]
Using `bd` close the tab with its all buffers not only one buffer. How could you close only one buffer from a specific tab?

**Comment by kdheepak** [comment]
It appears that `:bd<CR>` deletes the buffer, as well as closes the window. And if that's the last window it deletes the tab. I'd recommend using something like https://github.com/moll/vim-bbye to handle this. I use `<leader>bd` to map to `:Bdelete<CR>` and that seems to work well, i.e. deletes the buffers and switches to a different open buffer without affecting the tabs or the window arrangement.

**Comment by kdheepak** [comment]
I'll close this since this is not an issue with this plugin, this is unfortunately just the way vim works.
