### ISSUE TITLE
Command to create new tab with specified name

### ISSUE THREAD

**Issue by nguyentritai2906** [kdheepak/tabline.nvim#18]
Hi, thank you for a great plugin.
Like the title says, I find myself more of `:TablineTabNew` -> `:TablineTabRename` then Telescope to open files than create new tab with files.
Is it possible to do it in one command?

**Comment by kdheepak** [comment]
Yeah it should be straightforward to do that. You can even write it in your vimrc. I’ll post an update here when I get to it.

**Comment by nguyentritai2906** [comment]
Actually I think I've done it. It works but I'm not sure it's the right way to do it.

```lua
function M.tab_nnew(name)
  vim.cmd("tablast | tabnew")
  M._new_tab_data()
  local data = vim.fn.json_decode(vim.g.tabline_tab_data)
  data[vim.fn.tabpagenr()].name = name
  vim.g.tabline_tab_data = vim.fn.json_encode(data)
  vim.cmd([[redrawtabline]])
end
```
