### ISSUE TITLE
lualine tabline support doesn't work

### ISSUE THREAD

**Issue by mystilleef** [kdheepak/tabline.nvim#3]
Tabline support with `lualine` doesn't work for me. I tested with the minimal configuration below. It works well otherwise. I also attached a screenshot. I use the latest `Neovim` nightly.

### Minimal configuration

```lua
require("lualine").setup({
  tabline = {
    lualine_a = { require("tabline").buffers },
    lualine_b = { "mode" },
    lualine_c = {},
    lualine_x = {},
    lualine_y = {},
    lualine_z = { require("tabline").tabs },
  },
})
require("tabline").setup({ enable = false })
```

### Screenshot

![Screenshot from 2021-08-08 15-36-10](https://user-images.githubusercontent.com/273399/128643809-25753906-785e-4f62-8258-a5ac149939a6.png)

### Nvim version

```
NVIM v0.6.0-dev+108-g5130bc071
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.6.0~dev.108.g5130bc071/x86_64-redhat-linux-gnu/config -I/builddir/build/BUILD/neovim-0.6.0~dev.108.g5130bc071/src -I/usr/include -I/usr/include/lua-5.1 -I/builddir/build/BUILD/neovim-0.6.0~dev.108.g5130bc071/x86_64-redhat-linux-gnu/src/nvim/auto -I/builddir/build/BUILD/neovim-0.6.0~dev.108.g5130bc071/x86_64-redhat-linux-gnu/include
Compiled by mockbuild

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by kdheepak** [comment]
I had a typo in the README. You need the following configuration:

```lua
require("lualine").setup({
  tabline = {
    lualine_a = { require("tabline").tabline_buffers },
    lualine_b = { "mode" },
    lualine_c = {},
    lualine_x = {},
    lualine_y = {},
    lualine_z = { require("tabline").tabline_tabs },
  },
})
require("tabline").setup({ enable = false })
```

However, it is not displaying the way I thought it would. I thought I had this working earlier but maybe some changes I made along the way broke something. I will look into it. For now, I've removed the section in the README. I'll leave this issue open to track this bug.

**Comment by kdheepak** [comment]
I fixed one of the issues. You should be able to use the following:

```lua
require'lualine'.setup {
...
  tabline = {
    lualine_a = { 'mode' },
    lualine_b = {},
    lualine_c = { require'tabline'.tabline_buffers },
    lualine_x = { require'tabline'.tabline_tabs },
    lualine_y = {},
    lualine_z = {},
  },
...
}
```

I haven't set it up to work in any section yet. It works best in `lualine_c` and `lualine_x` for buffers and tabs.

**Comment by mystilleef** [comment]
I still need to do more testing, but so far I've encountered one major bug. If I open multiple files from the terminal, `tabline` fails to load. This doesn't happen if I open files from inside `nvim`. I was able to screenshot this error message only twice. I've struggled to recreate the error message since.

![tabline_error](https://user-images.githubusercontent.com/273399/128760545-107c5fa5-456b-4479-a0a7-957cc8e47f37.png)

### Test configuration

```lua
require("lualine").setup({
  options = {
    icons_enabled = true,
    -- theme = "gruvbox_material",
    section_separators = { "", "" },
    component_separators = { "•", "•" },
    disabled_filetypes = {},
  },
  tabline = {
    lualine_a = { "hostname" },
    lualine_b = { "branch" },
    lualine_c = { require("tabline").tabline_buffers },
    lualine_x = { require("tabline").tabline_tabs },
    lualine_y = {
      {
        "diagnostics",
        sources = { "nvim_lsp" },
        sections = { "error", "warn", "info", "hint" },
        symbols = { error = " ", warn = " ", info = " ", hint = " " },
      },
      {
        "diff",
        symbols = { added = " ", modified = "柳", removed = " " },
      },
      -- { numbufs },
      "filetype",
      "fileformat",
      "encoding",
      "progress",
    },
    lualine_z = { "location" },
  },
})
require("tabline").setup({ enable = false })

vim.cmd([[
  augroup LualineTreeAutoGroup
    au!
    au CursorHold * redrawstatus
    au CursorHold * redrawtabline
  augroup end
]])

```

### Feedback

Depending on your separator style, `tabline_tabs` style may clash with components drawn after it. I see this problem with the default `lualine` styles. Not so much with my separator styles. Personally, I don't use tabs, so it's not an issue for me at all. I'll end up disabling it. I have it enabled just for testing.  

### Shrink or expand tabline buffer list?

My `tabline` mostly mirrors my `statusline`. I admit this is a peculiar use-case. But I really only need to see the current buffer and 1 or 2 buffers before and after it. The current behavior of `tabline_buffers` is to expand to fill up the `tabline` and push other components out of view. This is great for users using tabline_buffers exclusively. But for users using tabline_buffers to complement `lualine's tabline`, I think the majority of them would prefer that the buffer list shrinks to show only the current buffer when space is constrained. 

Other than that, fantastic work. This is looking superb. It handles my overloaded `tabline` gracefully. I'll do more testing later on.

![tabline_example](https://user-images.githubusercontent.com/273399/128765284-44f8886c-749d-4cad-9733-c4a88ef5d381.png)

Kudos!

**Comment by kdheepak** [comment]
I should be able to add a way to set the maximum number of buffers shown fairly easily. 

As for the other issue, I’ll look into it. You can use `: messages ` and it should show you all error messages printed out in nvim.

**Comment by kdheepak** [comment]
I've added a `max_bufferline_percent` option:

<img width="834" alt="Screen Shot 2021-08-11 at 6 36 37 AM" src="https://user-images.githubusercontent.com/1813121/129029699-9ae2b9d1-298f-49d3-b3ad-cb45270f9eba.png">

If you set it to a low value e.g. `10`, it'll show just one buffer or maybe two.

**Comment by kdheepak** [comment]
I'm closing this issue now. Thanks for the detailed comments and the reproducible example. It was easy to figure out what was going on using that. Let me know if anything else comes up. Feel free to open new issues.
