### ISSUE TITLE
Option to disable buffers (show only tabs)

### ISSUE THREAD

**Issue by BlackLight** [kdheepak/tabline.nvim#32]
As of now both buffers and tabs are shown in the tabline.

I would like an option to just show tabs. If I open a new empty tab and then I close it via `:q`, the only way to get it removed from the tabline is to show the open buffers via `:buffers` and then do a `:bd <number>`.

This is definitely a different pattern than the one implemented by vim and neovim, as well as any IDE out there - where closing a tab also removes the corresponding entry from the list of tabs.

While I may see the use case for treating tabs and buffers as one thing, I'd like at least an option to disable buffers in the tabline that have already been closed.

**Comment by kdheepak** [comment]
This feature is now available.
