### ISSUE TITLE
The padding space filename is inconsistant if no web icons

### ISSUE THREAD

**Issue by Wsine** [kdheepak/tabline.nvim#34]
Hi,

Appriactiate your work first. I wonder if it is possible to address the below problem using current customized options?

There are just 1 space on the right of filename while two on left side.

![image](https://user-images.githubusercontent.com/8842278/162918081-e2e01695-d967-41d0-b53e-2308924f5159.png)

I tried a lot but found nothing work, so I asked here. Thanks.

**Comment by kdheepak** [comment]
The spacing works well for these separators:

```
  component_left = "",
  component_right = "",
  section_left = "",
  section_right = "",
```

I'll need to look into why it isn't working well for your case. Can you share the separators you are using? 

Thanks for reporting this bug.

**Comment by Wsine** [comment]
Sure. Below is my config file together with lualine.

```lua
-- ==============================================
--              LuaLine config
-- ==============================================
require'tabline'.setup {
  options = {
    section_separators = {'', ''},
    component_separators = {'', ''},
    show_devicons = false,
    modified_icon = '* ',
  }
}
require'lualine'.setup {
  options = {
    icons_enabled = false,
    theme = 'nightfox',
    component_separators = { left = '|', right = '|' },
    section_separators = { left = '', right = '' },
    disabled_filetypes = {'NvimTree'}
  },
  tabline = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = { require'tabline'.tabline_buffers },
    lualine_x = { require'tabline'.tabline_tabs },
    lualine_y = {},
    lualine_z = {},
  }
}
```
