### ISSUE TITLE
Error trying to execute :TablineBufferNext and Previous

### ISSUE THREAD

**Issue by waldirborbajr** [kdheepak/tabline.nvim#37]
Error trying to execute :TablineBufferNext and Previous

NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

E5108: Error executing lua ...nvim/site/pack/packer/start/tabline.nvim/lua/tabline.lua:780: bad argument #1 to '
pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        ...nvim/site/pack/packer/start/tabline.nvim/lua/tabline.lua:780: in function 'buffer_next'
        [string ":lua"]:1: in main chunk

**Comment by kdheepak** [comment]
`M.buffers` in this line:

https://github.com/kdheepak/tabline.nvim/blob/b080ed3a507c76819f182b6936097b8158a4a715/lua/tabline.lua#L780

should be instantiated as a empty table at the very least, e.g. like here:

https://github.com/kdheepak/tabline.nvim/blob/b080ed3a507c76819f182b6936097b8158a4a715/lua/tabline.lua#L587

and should not be `nil`. Can you share your exact configuration?

**Comment by waldirborbajr** [comment]
My config it's very simple, you can take a look here.

https://gitlab.com/waldirborbajr/dotfiles/-/blob/main/nvim/lua/config/tabline.lua

**Comment by waldirborbajr** [comment]
And here the lualine:

https://gitlab.com/waldirborbajr/dotfiles/-/blob/main/nvim/lua/config/lualine.lua

**Comment by GregoryBai** [comment]
I encountered the same issue with the latest commit, fixed by setting the plugin's commit to: `bbaf9a97b24ae2d4f0c7d8751d5f28aa45332480`
![image](https://user-images.githubusercontent.com/60780439/163717933-e6dcfccf-d0d0-4e84-ab9c-408b6adbf311.png)

**Comment by waldirborbajr** [comment]
> I encountered the same issue with the latest commit, fixed by setting the plugin's commit to: `bbaf9a97b24ae2d4f0c7d8751d5f28aa45332480` ![image](https://user-images.githubusercontent.com/60780439/163717933-e6dcfccf-d0d0-4e84-ab9c-408b6adbf311.png)

Thanks, I'll do this for now.

**Comment by s-cerevisiae** [comment]
> `M.buffers` in this line:
> 
> https://github.com/kdheepak/tabline.nvim/blob/b080ed3a507c76819f182b6936097b8158a4a715/lua/tabline.lua#L780
> 
> should be instantiated as a empty table at the very least, e.g. like here:
> 
> https://github.com/kdheepak/tabline.nvim/blob/b080ed3a507c76819f182b6936097b8158a4a715/lua/tabline.lua#L587
> 
> and should not be `nil`. Can you share your exact configuration?

The latest commit (`b080ed3`) disables the whole tabline by default when there's only one tab, and `vim.o.tabline` is *not* called so the field stays uninitialized.
I'd also like to point out that defaults to this behavior is incorrect because the tabline shall show up when multiple buffers exist, no matter how many tabs there are.

**Comment by kdheepak** [comment]
I’ll revert it as soon as I’m back at my computer later today, it’s been a crazy few days for me and I haven’t been able to get to this yet.

**Comment by kdheepak** [comment]
Sorry for the inconvenience caused. I've been super swamped with things happening in my personal life and haven't been able to get to this. I reverted the PR and it seems to be working for me now. I'll make sure I test and push any fixes if I run into any further issues.

**Comment by waldirborbajr** [comment]
Thank you so much, it is working again.
