### ISSUE TITLE
Provide options to change section and component separators

### ISSUE THREAD

**Issue by mystilleef** [kdheepak/tabline.nvim#4]
`tabline` doesn't use the same section and component separators as `lualine`. An option to configure this during setup would be nice. Something like this. I added a screenshot, so you can see the differences in visual styles.

```lua
require("tabline").setup({
  enable = true,
  options = {
    section_separators = { "", "" },
    component_separators = { utf8.escape("%x{00B7}"), utf8.escape("%x{00B7}") },
  },
})
```

![Screenshot from 2021-08-08 16-20-10](https://user-images.githubusercontent.com/273399/128644735-3b7942be-5e56-4d52-9244-b444185a48ad.png)

**Comment by kdheepak** [comment]
Yes! I meant to add support for this and completely forgot about it. I’ll do it tonight.

**Comment by kdheepak** [comment]
I make a change in the referenced PR. You don't need to add any options. If `lualine` is installed and you've configured the separators over there, `tabline` will use the same.
